.gitignore
README.md
normalize.py
setup.py
tn/chinese/normalizer.py

[feat] support setup pkg

---

tn/chinese/test/cardinal_test.py
tn/chinese/test/char_test.py
tn/chinese/test/date_test.py
tn/chinese/test/fraction_test.py
tn/chinese/test/math_test.py
tn/chinese/test/measure_test.py
tn/chinese/test/money_test.py
tn/chinese/test/normalizer_test.py
tn/chinese/test/postprocessor_test.py
tn/chinese/test/preprocessor_test.py
tn/chinese/test/time_test.py
tn/chinese/test/token_parser_test.py
tn/chinese/test/whitelist_test.py

fix(unittest): [cr_id_skip] Fix tn unittest

---

runtime/processor/processor.cc
runtime/processor/token_parser.cc
runtime/processor/token_parser.h
runtime/test/token_parser_test.cc

refactor(runtime): [cr_id_skip] Support itn order

---

itn/chinese/inverse_normalizer.py
itn/chinese/rules/cardinal.py
itn/chinese/rules/date.py
itn/chinese/rules/fraction.py
itn/chinese/rules/measure.py
itn/chinese/rules/preprocessor.py
itn/chinese/rules/whitelist.py

refactor(itn): [cr_id_skip] Speed up compilation

---

tn/processor.py

fix https://github.com/wenet-e2e/WeTextProcessing/issues/45

[tn] fix escape symbol

---

runtime/patch/openfst/test/CMakeLists.txt

Plz see: https://github.com/kkm000/openfst/commit/1b5a9c4bbeb4bd09861f3d9c5cf4cc39e2f8b39c

[runtime] fix openfst patch

---

itn/chinese/inverse_normalizer.py
tn/chinese/normalizer.py

see https://github.com/wenet-e2e/WeTextProcessing/issues/96

[Tn&ITN] Fix issue #96

---

itn/chinese/rules/cardinal.py

fix https://github.com/wenet-e2e/WeTextProcessing/issues/128

fix(itn): 多个数字之间加空格

---

itn/chinese/rules/cardinal.py

fix(itn): ip address

---

tn/main.py

fix https://github.com/wenet-e2e/WeTextProcessing/issues/139

feat(tn): add args

---

tn/chinese/normalizer.py
tn/chinese/rules/whitelist.py
tn/main.py

fix https://github.com/wenet-e2e/WeTextProcessing/issues/142

feat(tn): remove_erhua

---

tn/chinese/data/default/whitelist.tsv

fix https://github.com/wenet-e2e/WeTextProcessing/issues/150

fix(tn): singer by2

---

tn/english/data/ordinal/digit.tsv
tn/english/data/ordinal/teen.tsv
tn/english/normalizer.py
tn/english/rules/ordinal.py
tn/english/test/data/ordinal.txt
tn/english/test/ordinal_test.py

[tn] english tn, support ordinal

---

tn/english/normalizer.py
tn/english/rules/cardinal.py
tn/english/rules/decimal.py
tn/english/test/data/decimal.txt
tn/english/test/decimal_test.py
tn/processor.py

[tn] english tn, support decimal

---

tn/english/normalizer.py
tn/english/rules/fraction.py
tn/english/test/data/fraction.txt
tn/english/test/fraction_test.py

[tn] english tn, support fraction

---

tn/english/data/time/__init__.py
tn/english/data/time/suffix.tsv
tn/english/data/time/zone.tsv
tn/english/normalizer.py
tn/english/rules/time.py
tn/english/test/data/time.txt
tn/english/test/time_test.py

[tn] english tn, support time

---

tn/english/normalizer.py

[tn] set whitelist weight = 1.0

---

runtime/processor/wetext_processor.cc
runtime/processor/wetext_token_parser.cc
runtime/processor/wetext_token_parser.h

[runtime] support english tn

---

tn/english/rules/punctuation.py
tn/english/test/data/normalizer.txt

fix https://github.com/wenet-e2e/WeTextProcessing/issues/250

[tn] english, fix <p>

---

requirements.txt
tn/english/normalizer.py

fix https://github.com/wenet-e2e/WeTextProcessing/issues/245

[install] upgrade pynini to 2.1.6

---

tn/english/data/whitelist/tts.tsv

fix https://github.com/wenet-e2e/WeTextProcessing/issues/248

[tn] add whitelist for you're

---

tn/english/normalizer.py
tn/english/test/data/normalizer.txt

fix https://github.com/wenet-e2e/WeTextProcessing/issues/261

[tn] delete prefix space

---

itn/chinese/rules/cardinal.py

fix  https://github.com/wenet-e2e/WeTextProcessing/issues/265

[itn] fix 十三五
